name: Print Secret
on:
  push:
    branches: [ main ]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        env:
          KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: |
          echo "$KEY" | base64
